// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsaZ83crppK9RMA13o1p7Pgluz4HfpGKQ',
    appId: '1:652440343004:web:c45f2b5bb367f452ac3f19',
    messagingSenderId: '652440343004',
    projectId: 'meat-shop-b4d6d',
    authDomain: 'meat-shop-b4d6d.firebaseapp.com',
    storageBucket: 'meat-shop-b4d6d.appspot.com',
    measurementId: 'G-2MJR761QK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO4udhXfWJhZ5cNGmL_Kaq2cZ2BatvM9g',
    appId: '1:652440343004:android:18ec3eba39ee2c70ac3f19',
    messagingSenderId: '652440343004',
    projectId: 'meat-shop-b4d6d',
    storageBucket: 'meat-shop-b4d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzzPlRpgIdfFkY9GS_OOMxK35qDpK4vmE',
    appId: '1:652440343004:ios:e8674eba1145b45dac3f19',
    messagingSenderId: '652440343004',
    projectId: 'meat-shop-b4d6d',
    storageBucket: 'meat-shop-b4d6d.appspot.com',
    iosBundleId: 'com.flit.meatShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzzPlRpgIdfFkY9GS_OOMxK35qDpK4vmE',
    appId: '1:652440343004:ios:98ddfc74ad0105cdac3f19',
    messagingSenderId: '652440343004',
    projectId: 'meat-shop-b4d6d',
    storageBucket: 'meat-shop-b4d6d.appspot.com',
    iosBundleId: 'com.flit.meatShopApp.RunnerTests',
  );
}
